sudo: required
dist: trusty
language: ruby
rvm:
 - 2.3.3
before_install:
 - sudo apt-get update
 - sudo apt-get install chromium-chromedriver
 - gem update --system
 - gem install bundler
before_script:
  - "export PATH=$PATH:/usr/lib/chromium-browser/"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

gemfile: gemfile
